### ISSUE TITLE
does not render other person stream

### ISSUE THREAD

**Issue by muazazhar** [zolomohan/react-native-agora-livestreaming-app#1]
It does not render other person video stream. it only renders caller's video not receiver's. It is only showing one user's stream

**Comment by zolomohan** [comment]
This is a livestreaming application, thus only the broadcaster's video is displayed to everyone. 
Please take a look at [https://github.com/zolomohan/rn-agora-video-conference-app](https://github.com/zolomohan/rn-agora-video-conference-app) for a video calling app.
